# -*- coding: utf-8 -*-
"""perfect_square

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyXy1D7-o2kKzFopA99l47R72x_rexkQ
"""

def sqrt(p,cnt):
  t=(int)(math.sqrt(p))
  p=p-(t**2)
  cnt+=1
  if p==1:
    return 1
  elif p==0:
    return cnt
  else:
    return sqrt(p,cnt)

def check(r):
  global ip
  cnt=1
  p=ip-(r**2)
  if p==1:
    return 2
  else:
    for i in range(2,(int)(math.sqrt(p))+1):
      if p%i==0:
        t=sqrt(p,cnt)
        if(t==1):
          break
        else:
          return t
    return check(r-1)

import math
ip=int(input())
r=(int)(math.sqrt(ip))
p=check(r)
print(p)

